
#=========================
#=== SMART IRRIGATION SETTINGS
#=========================
type: entities
entities:

  - type: custom:hui-element
    card_type: vertical-stack
    cards:

      #=== Temperature Settings
      - !include
          - ../../../titles.yaml
          - title: SMART IRRIGATION SETTINGS
            font_size: 18px
            font_family: Oswald
            color: var(--secondary-text-color)
            margin_top: -1em
            margin_bottom: -1em
            border_left_color: var(--accent-color)

      #=== Number of days to use
      # - !include
      #     - ../item_settings_line.yaml
      #     - entity: input_number.irrigation_days_of_temp_history_used
      #       name: Number of days data to use
      #       label: (0 to 4) If zero only the temperature today is used

      #=== Temperature Baseline
      # - !include
      #     - ../item_settings_line.yaml
      #     - entity: input_number.irrigation_temperature_baseline
      #       name: Baseline temperature
      #       label: Exceeding this temperature increases the watering time
      #       unit: °C

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------

      #=== Smart irrigation model data
      - !include
          - ../../../titles.yaml
          - title: MODEL DATA
            font_size: 18px
            font_family: Oswald
            color: var(--secondary-text-color)
            margin_bottom: -1em
            border_left_color: var(--accent-color)

      #=== Daily adjusted run time
      - !include
          - ../item_settings_line.yaml
          - entity: sensor.smart_irrigation_daily_adjusted_run_time
            name: Daily adjusted run time
            label: Calculated at cycle start.
            unit: s
            round: 2
            tap_action: none

      #=== Hourly adjusted run time
      - !include
          - ../item_settings_line.yaml
          - entity: sensor.smart_irrigation_hourly_adjusted_run_time
            name: Hourly adjusted run time
            round: 1
            unit: s
            tap_action: none

      #=== Evapotranspiration
      - !include
          - ../item_settings_line.yaml
          - entity: sensor.smart_evapotranspiration
            name: Evapotranspiration
            round: 1
            tap_action: none
      #=== Precipitation 24 hours
      - !include
          - ../item_settings_line.yaml
          - entity: sensor.aemet_precipitation_daily
            name: 24 hours precipitation
            round: 1
            tap_action: none

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------


      #=== Forecast vs. Actual High Temperature
      - !include
          - ../../../titles.yaml
          - title:  IRRIGATION RATES - <font color=IndianRed>Hourly</font> vs. <font color=SteelBlue>Daily</font>
            font_size: 18px
            font_family: Oswald
            color: var(--secondary-text-color)
            margin_bottom: -1.5em
            border_left_color: var(--accent-color)

      #=== Irrigation times
      - !include item_settings_smartirrigation_graph.yaml

      #=== Precipitation
      - !include item_settings_smartirrigation_graph2.yaml


      # #-------------------------
      # - type: custom:hui-element
      #   row_type: divider
      # #-------------------------


      # #=== Temperature History
      # - !include
      #     - ../../../titles.yaml
      #     - title: TEMPERATURE HISTORY
      #       font_size: 18px
      #       font_family: Oswald
      #       color: var(--secondary-text-color)
      #       margin_bottom: -1em
      #       border_left_color: var(--accent-color)

      # #=== High Temperature Yesterday
      # - !include
      #     - ../item_settings_line.yaml
      #     - entity: input_number.irrigation_high_temp_1
      #       name: Yesterday
      #       round: 1
      #       unit: °C
      #       tap_action: none
      #       padding: 0.5em 0em 0.5em 0em

      # #=== High Temperature 2 Days Ago
      # - !include
      #     - ../item_settings_line.yaml
      #     - entity: input_number.irrigation_high_temp_2
      #       name: Two days ago
      #       round: 1
      #       unit: °C
      #       tap_action: none

      # #=== High Temperature 3 Days Ago
      # - !include
      #     - ../item_settings_line.yaml
      #     - entity: input_number.irrigation_high_temp_3
      #       name: Three days ago
      #       round: 1
      #       unit: °C
      #       tap_action: none

      # #=== High Temperature 4 Days Ago
      # - !include
      #     - ../item_settings_line.yaml
      #     - entity: input_number.irrigation_high_temp_4
      #       name: Four days ago
      #       unit: °C
      #       round: 1
      #       tap_action: none

style: >
  ha-card {
    box-shadow: none;
  }
