
#=========================
#=== TEMPERATURE SETTINGS
#=========================
type: entities
entities:

  - type: custom:hui-element
    card_type: vertical-stack
    cards:

      #=== Temperature Settings
      - type: custom:button-card  
        show_icon: false
        name: TEMPERATURE SETTINGS
        tap_action:
          action: none
        styles: &title_style
          card:
            - color: var(--secondary-text-color)
            - box-shadow: none
            - border-radius: 0em
            - background: none
            - padding-top: 0em
            - padding-bottom: 0em
            - padding-left: 0.5em
            - font-family: >
                [[[
                  return states['input_text.irrigation_ui_font_family'].state
                ]]]
            - font-size: 18px
          name:
            - justify-self: start
            - border-left: 3px solid var(--accent-color)
            - padding-left: 0.5em

      #=== Number of days to use
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_days_of_temp_history_used
            name: Number of days data to use
            label: (0 to 4) If zero only the temperature today is used

      #=== Temperature Baseline
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_temperature_baseline
            name: Baseline temperature
            label: Exceeding this temperature increases the watering time
            padding: 0em 0em 0.3em 0em

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------

      #=== Temperature Data
      - type: custom:button-card  
        show_icon: false
        name: TEMPERATURE DATA
        tap_action:
          action: none
        styles: *title_style

      #=== Temperature Multiplier
      - !include
          - ../item_settings_multiplier_line.yaml
          - entity: input_number.irrigation_temp_multiplier
            name: "Current Multiplier ( \U00002139 )"
            label: Calculated based on temperature and baseline

      #=== Highest Forecast High Temperature Today
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_temperature_highest_forecast_high_temp_today
            name: Highest forecasted temperature today
            round: 1
            tap_action: none

  #=== Highest Actual Temperature Today
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_temperature_highest_actual_temp_today
            name: Highest actual temperature recorded today
            round: 1
            tap_action: none
            padding: 0em 0em 0.3em 0em


      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------


      #=== Forecast High vs. Actual Temperature
      - type: custom:button-card  
        show_icon: false
        name:  HIGH TEMPERATURE - <font color=IndianRed>Forecast</font> vs. <font color=SteelBlue>Actual</font>
        tap_action:
          action: none
        styles: *title_style

      #=== Forecast vs. Actual High Temperature Graph
      - !include item_settings_temperature_graph.yaml

      #=== Use Forecast High Temperature
      - !include item_settings_use_forecast_high_temp.yaml


      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------


      #=== Temperature History
      - type: custom:button-card  
        show_icon: false
        name: HIGH TEMPERATURE HISTORY
        tap_action:
          action: none
        styles: *title_style

      - type: custom:button-card
        show_icon: false
        name: Zero days data selected (only using today)
        tap_action:
          action: none
        styles:
          card:
            - color: var(--primary-text-color)
            - border-radius: 0em
            - background: none
            - padding-top: 0em
            - padding-bottom: 0em
            - padding-left: 0.5em
            - font-family: >
                [[[
                  return states['input_text.irrigation_ui_font_family'].state
                ]]]
            - font-size: 14px
            - display: >
                [[[ return states['input_number.irrigation_days_of_temp_history_used'].state > 0 ? 'none' : 'unset' ]]]
          name:
            - justify-self: start
            - padding-left: 1.2em
        

      #=== High Temperature Yesterday
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_high_temp_1
            name: Yesterday
            round: 1
            tap_action: none
            display_condition: "[[[ return states['input_number.irrigation_days_of_temp_history_used'].state < 1 ? 'none' : 'unset' ]]]"

      #=== High Temperature 2 Days Ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_high_temp_2
            name: Two days ago
            round: 1
            tap_action: none
            display_condition: "[[[ return states['input_number.irrigation_days_of_temp_history_used'].state < 2 ? 'none' : 'unset' ]]]"

      #=== High Temperature 3 Days Ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_high_temp_3
            name: Three days ago
            round: 1
            tap_action: none
            display_condition: "[[[ return states['input_number.irrigation_days_of_temp_history_used'].state < 3 ? 'none' : 'unset' ]]]"

      #=== High Temperature 4 Days Ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_high_temp_4
            name: Four days ago
            round: 1
            tap_action: none
            display_condition: "[[[ return states['input_number.irrigation_days_of_temp_history_used'].state < 4 ? 'none' : 'unset' ]]]"

style: >
  ha-card {
    box-shadow: none;
  }
