# Lovelace_gen

#=======================================
#=== Boolean Check Box With Entity Icon
#=======================================
type: custom:button-card
color_type: icon
entity: {{ entity }}
show_state: false
show_name: true
name: {{ name }}
show_icon: true
size: 50%
tap_action:
  action: toggle
styles:
  grid:
    - grid-template-areas: '"i n check_box"'
    - grid-template-columns: 20% auto 15%
    - grid-template-rows: 1fr
  img_cell:
    - padding: 0em
  card:
    - font-family: "[[[ return states['input_text.irrigation_ui_font_family'].state ]]]"
    - padding: 0em
    - height: 2.5em
    - font-size: 14px
    - border-radius: 5px
  name:
    - justify-self: start
  custom_fields:
    check_box:
      - padding: 0.4em
custom_fields:
  check_box: >
    [[[
      var on_icon = 'mdi:checkbox-marked';
      var off_icon = 'mdi:checkbox-blank-outline';
      
      if (entity.state == 'on')
          return '<ha-icon icon="' + on_icon + '"></ha-icon>';
      else
          return '<ha-icon icon="' + off_icon + '"></ha-icon>';
    ]]] 
state:
  - value: 'on'
    name: {{ on_name }}
    styles:
      card:
        - background-color: var(--primary-background-color)
        - border: 1px solid var(--accent-color)
  - value: 'off'
    name: {{ off_name }}
    styles:
      card:
        - color: var(--secondary-text-color)
      icon:
        - color: var(--secondary-text-color)

