
#================
#=== Input Texts
#================
input_text:

  irrigation_external_sensor_controller_wifi:
    name: Irrigation Controller WiFi Signal Strength
    icon: mdi:wifi
    min: 0
    max: 100


#==================
#=== Input Numbers
#==================
input_number:

  irrigation_controller_offline_wait: 
    name: Time to wait for controller when offline
    min: 1
    max: 60
    step: 1
    mode: box
    unit_of_measurement: secs
    icon: mdi:timer-sand


#================
#=== Automations
#================
automation:

  #==============================================
  #=== Set default Controller WiFi Signal Sensor
  #==============================================
  - alias: Irrigation Set Default Controller WiFi Signal Sensor
    trigger:
      - platform: homeassistant
        event: start

      - platform: state
        entity_id: input_text.irrigation_external_sensor_controller_wifi
        to: ''

    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_text.irrigation_external_sensor_controller_wifi
          state: 'unknown'

        - condition: state
          entity_id: input_text.irrigation_external_sensor_controller_wifi
          state: ''

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_external_sensor_controller_wifi
          value: sensor.esphome_irrigation_controller_wifi_signal


  #===================================================
  #=== Synchronise the Zone Switch Sensors
  #=== These need to be updated as they are templated
  #=== on the switch name provided through the UI and
  #=== are used in the history statistics sensors 
  #===================================================
  - alias: Irrigation Synchronise Sensor Zone Switches
    mode: queued
    trigger:
      - platform: event
        event_type: state_changed

    condition:
      - condition: template
        value_template: >
          {{ 
            trigger.event.data.entity_id in [
              'input_text.irrigation_zone1_switch_entity_id',
              'input_text.irrigation_zone2_switch_entity_id',
              'input_text.irrigation_zone3_switch_entity_id',
              'input_text.irrigation_zone4_switch_entity_id',
              'input_text.irrigation_zone5_switch_entity_id',
              'input_text.irrigation_zone6_switch_entity_id',
              'input_text.irrigation_zone7_switch_entity_id',
              'input_text.irrigation_zone8_switch_entity_id',
              states('input_text.irrigation_zone1_switch_entity_id'),
              states('input_text.irrigation_zone2_switch_entity_id'),
              states('input_text.irrigation_zone3_switch_entity_id'),
              states('input_text.irrigation_zone4_switch_entity_id'),
              states('input_text.irrigation_zone5_switch_entity_id'),
              states('input_text.irrigation_zone6_switch_entity_id'),
              states('input_text.irrigation_zone7_switch_entity_id'),
              states('input_text.irrigation_zone8_switch_entity_id')
            ]
          }}

    action:
      - service: homeassistant.update_entity
        data_template:
          entity_id: >
            {% if states('input_text.irrigation_zone1_switch_entity_id') in trigger.event.data.entity_id %}
              sensor.irrigation_sensor_zone1_switch
            {% elif states('input_text.irrigation_zone2_switch_entity_id') in trigger.event.data.entity_id %}
              sensor.irrigation_sensor_zone2_switch
            {% elif states('input_text.irrigation_zone3_switch_entity_id') in trigger.event.data.entity_id %}
              sensor.irrigation_sensor_zone3_switch
            {% elif states('input_text.irrigation_zone4_switch_entity_id') in trigger.event.data.entity_id %}
              sensor.irrigation_sensor_zone4_switch
            {% elif states('input_text.irrigation_zone5_switch_entity_id') in trigger.event.data.entity_id %}
              sensor.irrigation_sensor_zone5_switch
            {% elif states('input_text.irrigation_zone6_switch_entity_id') in trigger.event.data.entity_id %}
              sensor.irrigation_sensor_zone6_switch
            {% elif states('input_text.irrigation_zone7_switch_entity_id') in trigger.event.data.entity_id %}
              sensor.irrigation_sensor_zone7_switch
            {% elif states('input_text.irrigation_zone8_switch_entity_id') in trigger.event.data.entity_id %}
              sensor.irrigation_sensor_zone8_switch
            {% else %}
              none
            {% endif %}
