
#================
#=== Automations
#================
automation:

  #========================================================================
  #=== Run a cycle if it is enabled and at the right time on the right day
  #=== Or a Manual run is requested
  #========================================================================
  - alias: Irrigation Triggered

    #================================================
    #=== TRIGGERS
    #===    At scheduled Cycle 1 or Cycle 2 Run Time
    #===    Cycle 3 manually started
    #================================================
    trigger:
      #=== Cycle 1 Start Time
      - platform: template
        value_template: >
          {% set start_time = states('sensor.irrigation_cycle1_start_time_in_seconds') | int %}
          {% set start_time = start_time | timestamp_custom('%H:%M', false) %}
          {{ states('sensor.time') == start_time }}

      #=== Cycle 2 Start Time
      - platform: template
        value_template: >
          {% set start_time = states('sensor.irrigation_cycle2_start_time_in_seconds') | int %}
          {% set start_time = start_time | timestamp_custom('%H:%M', false) %}
          {{ states('sensor.time') == start_time }}

      #=== Cycle 3 Manual Run
      - platform: state
        entity_id: input_boolean.irrigation_cycle3_running
        to: 'on'

    #===================================================
    #=== CONDITIONS
    #===    Master Control switch must be On
    #===    No other cycle is currently running
    #===    The cycle is enabled
    #===    It is not raining now if option is selected
    #===================================================
    condition:
      #=== Only continue if Master Control Switch is on
      - condition: state
        entity_id: input_boolean.irrigation_master_control_switch
        state: 'on'

      #=== Only continue if Cycles 1 and 2 are not running
      #=== NOTE: Cycle 3 is prevented from running if either Cycle 1 or 2 are running by its Start button
      - condition: state
        entity_id: input_boolean.irrigation_cycle1_running
        state: 'off'

      - condition: state
        entity_id: input_boolean.irrigation_cycle2_running
        state: 'off'

      #=== Check this cycle is enabled. NOTE: don't check this for cycle 3
      - condition: template
        value_template: >
          {% set start_time_cycle1 = states('sensor.irrigation_cycle1_start_time_in_seconds') | int %}
          {% set start_time_cycle1 = start_time_cycle1 | timestamp_custom('%H:%M', false) %}
          {% if states('sensor.time') == start_time_cycle1 %}
            {% set cycle = 'cycle1' %}
          {% else %}
            {% set cycle = 'cycle2' %}
          {% endif %}

          {% if 'cycle3' in trigger.entity_id %}
            True
          {% elif states('input_boolean.irrigation_' ~ cycle ~ '_schedule_enabled') =='on' %}
            True
          {% else %}
            False
          {% endif %}

      #=== Check it is not raining if that option is enabled. NOTE: don't check this for cycle 3
      - condition: template
        value_template: >
          {% if 'cycle3' in trigger.entity_id %}
            True
          {% elif states('input_boolean.irrigation_ignore_schedule_if_raining') == 'off' %}
            True
          {% elif states('input_boolean.irrigation_ignore_schedule_if_raining') == 'on' and
                  states(states('input_text.irrigation_external_sensor_raining_now')) == 'off' %}
            True
          {% else %}
            False
          {% endif %}


    #===============================================
    #=== ACTIONS
    #===    Indicate to system that cycle is runing
    #===============================================
    action:
      #==================================================
      # Update Smart Irrigation for the day
      #==================================================
      - service: smart_irrigation.smart_irrigation_calculate_daily_adjusted_run_time
      #==================================================
      # Wait 5 seconds to calculate irrigation
      #==================================================
      - delay: '00:00:05'
      #== Set the cycle to be running
      - service: homeassistant.turn_on
        data_template:
          entity_id: >
            {% set start_time_cycle1 = states('sensor.irrigation_cycle1_start_time_in_seconds') | int %}
            {% set start_time_cycle1 = start_time_cycle1 | timestamp_custom('%H:%M', false) %}

            {% if 'cycle3' in trigger.entity_id %}
              {{ 'input_boolean.irrigation_cycle3_running' }}
            {% elif states('sensor.time') == start_time_cycle1 %}
              {{ 'input_boolean.irrigation_cycle1_running' }}
            {% else %}
              {{ 'input_boolean.irrigation_cycle2_running' }}
            {% endif %}